version: "3.9"
services:
  debian:
    hostname: debian
    build: 
      context: .
      dockerfile: Dockerfile-debian
    ports: 
      - "2222:22"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    privileged: true
  fedora:
    hostname: fedora
    build: 
      context: .
      dockerfile: Dockerfile-fedora
    ports: 
      - "3333:22"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    privileged: true
  arch:
    hostname: arch
    build: 
      context: .
      dockerfile: Dockerfile-arch
    ports: 
      - "4444:22"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    privileged: true
 
