FROM fedora:latest

RUN sed -i "/tsflags=nodocs/d" /etc/dnf/dnf.conf  #get docs with pkgs
RUN dnf install -y openssh-server openssh-clients 
RUN ssh-keygen -A

RUN dnf install -y sudo git tmux man man-pages docker zsh
RUN useradd -s /bin/zsh dev
RUN usermod -aG wheel dev
RUN echo "dev:password" | chpasswd

RUN dnf -y install ninja-build libtool autoconf automake cmake gcc gcc-c++ make pkgconfig unzip patch gettext curl
RUN git clone https://github.com/neovim/neovim /home/dev/neovim
WORKDIR /home/dev/neovim
RUN git checkout stable
RUN CMAKE_BUILD_TYPE=Release make -j8
RUN make install


RUN git clone https://github.com/chrisharper/dotfiles /home/dev/dotfiles
WORKDIR /home/dev/dotfiles
RUN git submodule update --init --recursive 
RUN git remote set-url origin ssh://git@github.com/chrisharper/dotfiles
RUN chown dev:dev -R /home/dev
RUN sudo -u dev /home/dev/dotfiles/install

EXPOSE 22
CMD ["/usr/sbin/sshd","-D"]
